FROM node:22

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./
COPY tsconfig.json next.config.ts ./
RUN npm install turbo --global
# Installer les dépendances du projet
RUN npm install && npm cache clean --force

# Copier le reste du code source
COPY . .

# Exposer le port
EXPOSE 3000

# Commande de démarrage
CMD ["npm", "run", "dev", "--", "--port", "3000"] 