version: "3"

services:
  # Service pour le frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/.env:/app/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/snowledge
  # Service pour le backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      # Monter le code source en préservant node_modules
      - ./backend:/app
      - /app/node_modules
      - ./backend/.env:/app/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/snowledge
