version: "3"

services:
  # Service pour le frontend
  frontend:
    build:
      context: . # On part de la racine du monorépo
      dockerfile: apps/frontend/Dockerfile.dev
    volumes:
      - ./apps/frontend:/app
      - node_modules_frontend:/app/node_modules
      - ./apps/frontend/.env:/app/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/snowledge
  # Service pour le backend

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    volumes:
      - ./apps/backend:/app
      - node_modules_backend:/app/node_modules
      - ./apps/backend/.env:/app/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/snowledge

volumes:
  node_modules_frontend:
  node_modules_backend:
