FROM node:22

WORKDIR /app

# Copier les fichiers de dépendances de tout le monorepo
COPY package*.json ./
COPY turbo.json ./
COPY apps/frontend/package*.json ./apps/frontend/
COPY packages/ui/package*.json ./packages/ui/
# Ajoute ici les autres packages si besoin

RUN npm install turbo --global

# Installer les dépendances à la racine (pour les workspaces)
RUN npm install && npm cache clean --force

# Copier tout le code source du monorepo
COPY . .

WORKDIR /app

EXPOSE 3000

# Commande de démarrage
CMD ["npm", "run", "dev"]