FROM node:22-alpine3.21 AS base

RUN npm install -g npm@latest @nestjs/cli

FROM base AS prune
RUN apk update
RUN apk add --no-cache libc6-compat
WORKDIR /app
RUN npm install turbo --global
COPY . .
RUN turbo prune backend --docker

FROM base AS installer
RUN apk update
RUN apk add --no-cache libc6-compat
WORKDIR /app
# Copier les fichiers de dépendances
COPY --from=prune /app/out/json/ .
COPY apps/backend/package*.json ./
# Installer NestJS CLI globalement
RUN npm install

# Copier le reste du code source
COPY --from=prune /app/out/full/ .
COPY turbo.json turbo.json

RUN npx turbo run build --filter=backend^... --no-cache

FROM base AS runner
WORKDIR /app

COPY --from=installer /app .

# Exposer le port
EXPOSE 4000

# Commande de démarrage
CMD ["npm", "run", "dev"]