FROM node:22-alpine3.21 AS base

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./
COPY turbo.json ./
COPY apps/backend/package*.json ./apps/backend/
COPY packages/logger/package*.json ./packages/logger/
# Ajoute ici les autres packages si besoin

RUN npm install turbo --global

# Installer NestJS CLI globalement
RUN npm install -g @nestjs/cli

# Installer les dépendances du projet
RUN npm install && npm cache clean --force

# Copier le reste du code source
COPY . .

WORKDIR /app

# Exposer le port
EXPOSE 4000

# Commande de démarrage
CMD ["npm", "run", "dev"]