import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ReactQueryClientProvider } from "@/utils/react-query-provider";
import { AppSidebar } from "@/components/sidebar/app-sidebar";
import Header from "@/components/shared/Header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <div className="flex min-h-screen min-w-full">
        <AppSidebar />
        <div className="flex-1 flex flex-col">
          <Header />
          <main className="flex-1 w-full">
            <ReactQueryClientProvider>
              <SidebarInset>{children}</SidebarInset>
            </ReactQueryClientProvider>
          </main>
        </div>
      </div>
    </SidebarProvider>
  );
}
